services:
  # --- BASE DE DONNÃ‰ES ---
  postgres:
    image: postgres:16-alpine
    container_name: petite-maison-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - petite-maison-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- GESTION DB ---
  adminer:
    image: adminer:latest
    container_name: petite-maison-adminer
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - postgres
    networks:
      - petite-maison-network

  # --- BACKEND API ---
  api:
    build: ./backend/api-service
    image: petite-maison-backend-image # ðŸ‘ˆ Force le nom de l'image
    container_name: petite-maison-backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./backend/api-service/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - petite-maison-network

  # --- FRONTEND REACT ---
  frontend:
    build: ./frontend
    image: petite-maison-frontend-image # ðŸ‘ˆ Force le nom de l'image
    container_name: petite-maison-frontend
    ports:
      - "3001:80"
    networks:
      - petite-maison-network

# --- CONFIGURATION RÃ‰SEAU ET VOLUMES ---
networks:
  petite-maison-network:
    name: petite-maison-network
    driver: bridge

volumes:
  postgres_data: