apiVersion: apps/v1
kind: Deployment
metadata:
  name: petite-maison-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # üõ†Ô∏è INIT CONTAINER : Pr√©pare le dossier persistant avec les bons droits
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /app/uploads && chmod -R 777 /app/uploads"]
          volumeMounts:
            - name: storage-uploads
              mountPath: /app/uploads
      
      containers:
        - name: api
          image: backend-petite-maison:v5
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: storage-uploads
              mountPath: /app/uploads
          env:
            # --- CONFIGURATION BASE DE DONN√âES (Via Secrets) ---
            - name: DB_HOST
              value: "postgres" # Doit correspondre au nom du service dans postgres-deployment.yaml
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: app-secrets, key: postgres-db } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: postgres-user } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: postgres-password } }
            - name: DB_PORT
              value: "5432"
            
            # --- CONFIGURATION SERVEUR ---
            - name: PORT
              value: "3000"
            - name: FRONTEND_URL
              value: "http://localhost:30001"
            
            # --- S√âCURIT√â JWT (Via Secrets) ---
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: jwt-secret } }
            - name: JWT_REFRESH_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: jwt-refresh-secret } }
      
      # üíæ D√âFINITION DU VOLUME PERSISTANT
      volumes:
        - name: storage-uploads
          persistentVolumeClaim:
            claimName: uploads-pvc # üëà C'est ici que la magie op√®re : fini les pertes d'images !

---
apiVersion: v1
kind: Service
metadata:
  name: petite-maison-backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 30000      # Port externe pour ton config.js
      targetPort: 3000 # Port interne de ton code Express