# ✅ SERVICE DE LA BASE DE DONNÉES
# Permet au Backend de communiquer avec Postgres via le nom d'hôte 'postgres'.
apiVersion: v1
kind: Service
metadata:
  # Doit correspondre à la variable DB_HOST de ton backend (souvent 'postgres')
  name: {{ .Values.database.host | default "postgres" }}
spec:
  # ClusterIP uniquement : La base de données ne doit JAMAIS être exposée sur le Web (Sécurité DevSecOps).
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: tcp-postgres
      port: 5432
      targetPort: 5432
      protocol: TCP