{{- if .Values.backend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-backend-hpa
  labels:
    app: backend
spec:
  # Cible le déploiement du backend
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-backend
  
  # Limites de réplication définies dans values.yaml
  minReplicas: {{ .Values.backend.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas | default 3 }}
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        # Déclenche le scale-up si la moyenne dépasse ce % (ex: 70%)
        averageUtilization: {{ .Values.backend.hpa.targetCPUUtilizationPercentage | default 70 }}
{{- end }}