{{- if not .Values.openshift.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    # On utilise une expression régulière pour capturer tout ce qui suit /api
    # et le renvoyer proprement au backend sans casser les routes.
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: petite-maison.local
    http:
      paths:
      # Route pour le FRONTEND
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-frontend
            port:
              number: 80
      # Route pour le BACKEND (API)
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-backend
            port:
              number: 3000
{{- end -}}