apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.uploadsSize }}
