apiVersion: v2
name: petite-maison-troc
description: Chart Helm pour le dÃ©ploiement orchestrÃ© (Frontend, Backend, Database) de l'application de troc.

# ğŸ·ï¸ TYPE : 'application' signifie que ce chart dÃ©ploie des services utilisables.
# (Par opposition Ã  'library' qui ne servirait qu'Ã  Ãªtre rÃ©utilisÃ© par d'autres charts).
type: application

# ğŸ“Œ VERSION DU CHART (v1.0.0) : 
# C'est la version de ton infrastructure Kubernetes. 
# Si tu ajoutes une Route ou un Service, tu incrÃ©mentes ici.
version: 1.0.0

# ğŸš€ APPVERSION (v1.0.0) : 
# C'est la version de ton code source (le tag de tes images Docker).
# Cela permet de savoir quel code tourne sur quelle infrastructure.
appVersion: "1.0.0"

# ğŸ‘¨â€ğŸ’» RESPONSABLE DU PROJET
maintainers:
  - name: Bakary
    email: badiaga.bakary13@gmail.com